<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="thunderdome" name="Sanity Test Group" tests="10" failures="2" timestamp="28 Jan 2016 14:51:18 GMT" time="8.525" errors="0">
  <testcase name="firstTestCaseB" time="0.103" classname="com.wordpressTest.tests.sanityTests.TestC"/>
  <testcase name="fifthTestCaseB" time="2.002" classname="com.wordpressTest.tests.sanityTests.TestB"/>
  <testcase name="firstTestCaseA" time="2.003" classname="com.wordpressTest.tests.sanityTests.TestA"/>
  <testcase name="secondWebSiteA" time="1.006" classname="com.wordpressTest.tests.sanityTests.TestA">
    <failure type="org.openqa.selenium.remote.SessionNotFoundException" message="Session ID is null. Using WebDriver after calling quit()?
Build info: version: &amp;apos;2.49.0&amp;apos;, revision: &amp;apos;365eeb44deba2067b1761c8862ef21d55250e063&amp;apos;, time: &amp;apos;2016-01-13 11:57:39&amp;apos;
System info: host: &amp;apos;thunderdome&amp;apos;, ip: &amp;apos;192.168.0.7&amp;apos;, os.name: &amp;apos;Mac OS X&amp;apos;, os.arch: &amp;apos;x86_64&amp;apos;, os.version: &amp;apos;10.10.5&amp;apos;, java.version: &amp;apos;1.8.0_45&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.49.0', revision: '365eeb44deba2067b1761c8862ef21d55250e063', time: '2016-01-13 11:57:39'
System info: host: 'thunderdome', ip: '192.168.0.7', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:134)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:363)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at com.wordpressTest.tests.sanityTests.TestA.secondWebSiteA(TestA.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- secondWebSiteA -->
  <testcase name="firstTestCaseB" time="2.005" classname="com.wordpressTest.tests.sanityTests.TestB"/>
  <testcase name="thirdTestCaseA" time="2.002" classname="com.wordpressTest.tests.sanityTests.TestA"/>
  <testcase name="secondTestCaseB" time="5.003" classname="com.wordpressTest.tests.sanityTests.TestC">
    <skipped/>
  </testcase> <!-- secondTestCaseB -->
  <testcase name="fourthTestCaseB" time="2.002" classname="com.wordpressTest.tests.sanityTests.TestB"/>
  <testcase name="secondTestCaseB" time="0.504" classname="com.wordpressTest.tests.sanityTests.TestB">
    <failure type="java.lang.AssertionError" message="Failing this Test">
      <![CDATA[java.lang.AssertionError: Failing this Test
	at org.testng.Assert.fail(Assert.java:94)
	at com.wordpressTest.tests.sanityTests.TestB.secondTestCaseB(TestB.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- secondTestCaseB -->
  <testcase name="thirdTestCaseB" time="2.005" classname="com.wordpressTest.tests.sanityTests.TestB"/>
</testsuite> <!-- Sanity Test Group -->
